:Author: Joseph
:Email: {josephdyoder@gmail.com}
:Date: 20/12/2023
:Revision: version#5.4.9
:License: Public Domain

= Project: {Alarm Clock}

Describe your project

== Step 1: Installation
Please describe the steps to install this project.

For example:

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact 11irishjs https://id.arduino.cc/11irishjs

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name               | Part number | Quantity
| U1 | FireBeetle Esp32-E V1.0 | 1234-abcd   | 1
| A1 | MAX 98357A I2S Amp      | 2345-asdf   | 1
| D1 | MicroSD card reader     | ABX00066    | 1
| R1 | 4ohm 3W speaker         | ABX00066    | 1
| L1 | RGB LED strip           | ABX00066    | 16 leds
| T1 | Thumb Tack              | ABX00066    | 5
| L1 | I2C OLED display        | ABX00066    | 1
| L1 | wire                    | ABX00066    | 2m
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
